name: flutter_spacex
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.18.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  go_router: ^5.2.3
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  equatable: ^2.0.0
  cupertino_icons: ^1.0.2
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  build_runner: ^2.3.2
  intl: ^0.17.0
  shimmer: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: 
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
        - asset: assets/fonts/Audiowide-Regular.ttf

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
